version: "3.9"

services:
  frontend:
    build: frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - database

  backend:
    build: lib_catalog
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django